blank_issues_enabled: true

contact_links:
  - name: ä½¿ç”¨é—®é¢˜ ğŸ—¨ï¸
    url: https://github.com/densen2014/BlazorMaui/discussions
    about: ä½¿ç”¨è¿‡ç¨‹ä¸­çš„ç–‘é—®è¯·å‘å¸ƒåˆ°è¿™é‡Œ
  - name: BootstrapBlazoré”™è¯¯ ğŸ“š
    url: https://github.com/dotnetcore/BootstrapBlazor/issues/new/choose
    about: å…³äºBootstrapBlazorç›¸å…³çš„é”™è¯¯è¯·æäº¤åˆ°è¿™é‡Œ